name: example
description: Demonstrates how to use the fl_webview plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fl_webview:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.0.1
  flutter_waya: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - lib/res/