name: example
description: Demonstrates how to use the fl_webview plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=3.24.0'

dependencies:
  fl_webview:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^6.2.0
  fl_scroll_view: ^0.0.3
  fl_extended: ^1.5.0
  file_picker: ^8.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/