name: example
description: Demonstrates how to use the fl_webview plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  fl_webview:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.3.1
  flutter_waya: ^7.5.2
  file_picker: ^5.3.2
  permission_handler: ^10.4.1

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/