name: fl_webview_example
description: Demonstrates how to use the fl_webview plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  fl_webview:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.2.0
  flutter_waya: ^1.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lib/res/