name: fl_webview
description: Based on webView_flutter plugin implemented by flutter supports Android and IOS
version: 1.1.2
repository: https://github.com/Wayaer/fl_webview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.webview
        pluginClass: FlWebViewPlugin
      ios:
        pluginClass: FlWebViewPlugin
      macos:
        pluginClass: FlWebViewPlugin