name: fl_webview
description: WebView for flutter supports Android and IOS
version: 0.0.1
repository: https://github.com/Wayaer/fl_webview

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: fl.webview
        pluginClass: FlWebviewPlugin
      ios:
        pluginClass: FlWebviewPlugin
