name: fl_webview
description: Based on webView_flutter plugin implemented by flutter supports Android and IOS
version: 0.2.5
repository: https://github.com/Wayaer/fl_webview

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: fl.webview
        pluginClass: FlWebViewPlugin
      ios:
        pluginClass: FlWebViewPlugin
