name: fl_webview
description: Based on webView_flutter plugin implemented by flutter supports Android and IOS
version: 0.6.1
repository: https://github.com/Wayaer/fl_webview

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.webview
        pluginClass: FlWebViewPlugin
      ios:
        pluginClass: FlWebViewPlugin
